name: Upstream Sync

on:
  schedule:
    - cron: "0 0 * * 1"
  workflow_dispatch:

permissions:
  actions: write
  contents: write

jobs:
  sync_latest_from_upstream:
    name: Sync latest commits from upstream repo
    runs-on: ubuntu-latest
    if: ${{ github.event.repository.fork }}

    steps:
      - name: Check out fork
        uses: actions/checkout@v4
        with:
          fetch-depth: 0
          ref: main

      - name: Merge upstream changes
        run: |
          git remote add upstream https://github.com/dreamhunter2333/cloudflare_temp_email.git
          git fetch upstream main
          git config user.name "github-actions[bot]"
          git config user.email "41898282+github-actions[bot]@users.noreply.github.com"
          git merge --no-edit --no-ff upstream/main
          git push origin HEAD:main

      - name: Trigger backend deployment
        run: gh workflow run backend_deploy.yaml --repo "${{ github.repository }}" --ref "${{ github.event.repository.default_branch }}"
        env:
          GH_TOKEN: ${{ github.token }}
